# Generated by Django 5.2.10 on 2026-03-15 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('users', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='follower_users', through='social.Follow', through_fields=('follower', 'following'), to=settings.AUTH_USER_MODEL),
        ),
    ]
