# Generated by Django 5.2.10 on 2026-03-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pro',
        ),
    ]
