# Generated by Django 5.2.10 on 2026-03-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
