# Generated by Django 5.2.10 on 2026-04-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='SALOM! | MEN', max_length=120, verbose_name='Salomlashuv')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=80, verbose_name='Familiya')),
                ('role', models.CharField(max_length=200, verbose_name='Lavozim / Texnologiyalar')),
                ('bio', models.TextField(verbose_name='Bio / Tavsif')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Rasm')),
                ('cta_label', models.CharField(default="Bog'lanish", max_length=60, verbose_name='CTA tugma matni')),
                ('cta_link', models.URLField(blank=True, verbose_name='CTA havolasi')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['order', 'id'],
            },
        ),
    ]
