# Generated by Django 5.2.10 on 2026-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='mission_logos/', verbose_name='Logo')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Our Mission',
                'verbose_name_plural': 'Our Missions',
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
