# Generated by Django 5.2.10 on 2026-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_missionsection_alter_teammember_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='greeting',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='missionsection',
            name='description_en',
            field=models.TextField(default='', verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='missionsection',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='missionsection',
            name='description_uz',
            field=models.TextField(default='', verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(default='', verbose_name='Bio (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(default='', verbose_name='Bio (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_uz',
            field=models.TextField(default='', verbose_name='Bio (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='cta_label_en',
            field=models.CharField(default='Connect', max_length=60, verbose_name='Tugma matni (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='cta_label_ru',
            field=models.CharField(default='Связаться', max_length=60, verbose_name='Tugma matni (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='cta_label_uz',
            field=models.CharField(default="Bog'lanish", max_length=60, verbose_name='Tugma matni (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_en',
            field=models.CharField(default='', max_length=80, verbose_name='Ism (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_ru',
            field=models.CharField(default='', max_length=80, verbose_name='Ism (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_uz',
            field=models.CharField(default='', max_length=80, verbose_name='Ism (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='greeting_en',
            field=models.CharField(default='HELLO! | I AM', max_length=120, verbose_name='Salomlashuv (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='greeting_ru',
            field=models.CharField(default='ПРИВЕТ! | Я', max_length=120, verbose_name='Salomlashuv (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='greeting_uz',
            field=models.CharField(default='SALOM! | MEN', max_length=120, verbose_name='Salomlashuv (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_en',
            field=models.CharField(default='', max_length=80, verbose_name='Familiya (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_ru',
            field=models.CharField(default='', max_length=80, verbose_name='Familiya (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_uz',
            field=models.CharField(default='', max_length=80, verbose_name='Familiya (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(default='', max_length=200, verbose_name='Lavozim (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Lavozim (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_uz',
            field=models.CharField(default='', max_length=200, verbose_name='Lavozim (UZ)'),
        ),
    ]
