# Generated by Django 5.2.10 on 2026-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_missionsection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nomi (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('price_uzs', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narxi (UZS)')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (USD)')),
                ('period_uz', models.CharField(help_text="e.g. 'oyiga'", max_length=50, verbose_name='Davr matni (UZ)')),
                ('period_ru', models.CharField(max_length=50, verbose_name='Davr matni (RU)')),
                ('period_en', models.CharField(max_length=50, verbose_name='Davr matni (EN)')),
                ('features_uz', models.TextField(help_text='Har bir xususiyat yangi qatorda', verbose_name='Xususiyatlar (UZ)')),
                ('features_ru', models.TextField(verbose_name='Xususiyatlar (RU)')),
                ('features_en', models.TextField(verbose_name='Xususiyatlar (EN)')),
                ('badge_text_uz', models.CharField(blank=True, max_length=50, verbose_name='Badge matni (UZ)')),
                ('badge_text_ru', models.CharField(blank=True, max_length=50, verbose_name='Badge matni (RU)')),
                ('badge_text_en', models.CharField(blank=True, max_length=50, verbose_name='Badge matni (EN)')),
                ('button_text_uz', models.CharField(max_length=50, verbose_name='Tugma matni (UZ)')),
                ('button_text_ru', models.CharField(max_length=50, verbose_name='Tugma matni (RU)')),
                ('button_text_en', models.CharField(max_length=50, verbose_name='Tugma matni (EN)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Bepulmi?')),
                ('is_most_popular', models.BooleanField(default=False, verbose_name='Eng mashhurmi?')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Tavsiya etiladimi?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order', 'id'],
            },
        ),
    ]
