# Generated by Django 5.2.10 on 2026-03-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_postcomment_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default="Do'konga o'tish", max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
